insert into news_article_ (id_, site_, title_, summary_, author_, published_) values
    ('tech-daily-quantum-error-correction',
     'tech-daily',
     'Quantum error correction crosses the break-even threshold',
     'A logical qubit has outlived its physical components for the first time in a production-scale device, removing one of the last theoretical objections to scalable quantum computing.',
     'Mara Lindqvist',
     timestamp with time zone '2026-08-28 07:15:00+00'),
    ('tech-daily-eu-cloud-portability-rules',
     'tech-daily',
     'EU cloud portability rules take effect',
     'Providers operating in the single market must now offer no-cost data egress and a documented migration path, a change expected to reshape long-term enterprise contracts.',
     'Tomas Brenner',
     timestamp with time zone '2026-08-30 11:40:00+00'),
    ('tech-daily-rust-in-the-kernel',
     'tech-daily',
     'Rust drivers reach parity in the mainline kernel',
     'The 7.2 merge window landed the last of the subsystem bindings, making it possible to write a complete storage driver without touching C.',
     'Priya Raghunathan',
     timestamp with time zone '2026-09-01 05:00:00+00'),
    ('science-weekly-enceladus-plume-chemistry',
     'science-weekly',
     'Enceladus plume yields complex organics',
     'Reanalysis of archived flyby data identifies branched hydrocarbons that are difficult to explain without sustained hydrothermal activity beneath the ice shell.',
     'Helen Osei',
     timestamp with time zone '2026-08-19 14:05:00+00'),
    ('science-weekly-antibiotic-from-soil-fungus',
     'science-weekly',
     'Soil fungus yields a new class of antibiotic',
     'The compound disrupts cell wall recycling rather than synthesis, and has so far failed to provoke resistance across forty passages in culture.',
     'Daniel Okonkwo',
     timestamp with time zone '2026-09-02 09:30:00+00'),
    ('world-tribune-danube-flood-defences',
     'world-tribune',
     'Danube states agree joint flood defence fund',
     'Eight riparian countries committed to a shared reservoir management scheme after a third consecutive year of record spring melt.',
     'Sofia Marchetti',
     timestamp with time zone '2026-08-25 16:20:00+00');
